const express = require('express');
const { spawn } = require('child_process');
const fs = require('fs');

const app = express();
const PORT = process.env.PORT || 3000;

// Tuner Configuration
// Adjust these adapter paths based on your system (e.g., /dev/dvb/adapter0, /dev/dvb/adapter1)
const TUNERS = [
    { id: 0, adapter: '/dev/dvb/adapter0', inUse: false },
    { id: 1, adapter: '/dev/dvb/adapter1', inUse: false }
];

// Mock Channel List - Replace with actual frequency data
const CHANNELS = [
    { number: '12.1', name: 'WINM HD', serviceId: 3 },
    { number: '12.2', name: 'SBN', serviceId: 4 },
    { number: '12.3', name: 'WEST', serviceId: 5 },
    { number: '12.4', name: 'COZI TV', serviceId: 6 },
    { number: '12.5', name: 'IONPlus', serviceId: 7 },
    { number: '12.6', name: 'JTV', serviceId: 8 },
    { number: '12.7', name: 'TOONS', serviceId: 9 },
    { number: '12.8', name: 'QUEST', serviceId: 10 },
    { number: '12.9', name: 'ONTV4U', serviceId: 11 },
    { number: '12.10', name: 'BIZTV', serviceId: 12 },
    { number: '12.11', name: 'GDT', serviceId: 13 },
    { number: '45.1', name: 'WFWC-CD', serviceId: 1001 },
    { number: '45.2', name: 'WFWC-CD', serviceId: 1002 },
    { number: '45.3', name: 'WFWC-CD', serviceId: 1003 },
    { number: '45.4', name: 'WFWC-CD', serviceId: 1004 },
    { number: '45.5', name: 'WFWC-CD', serviceId: 1005 },
    { number: '45.6', name: 'WFWC-CD', serviceId: 1006 },
    { number: '45.7', name: 'WFWC-CD', serviceId: 1007 },
    { number: '45.8', name: 'WFWC-CD', serviceId: 1008 },
    { number: '38.1', name: 'WEIJ HD', serviceId: 3 },
    { number: '38.4', name: 'COZI TV', serviceId: 6 },
    { number: '38.2', name: 'SBN', serviceId: 4 },
    { number: '38.8', name: 'QUEST', serviceId: 10 },
    { number: '38.5', name: 'IONPLUS', serviceId: 7 },
    { number: '38.9', name: 'ONTV4U', serviceId: 11 },
    { number: '38.7', name: 'TOONS', serviceId: 9 },
    { number: '38.10', name: 'BIZ TV', serviceId: 12 },
    { number: '38.3', name: 'WEST', serviceId: 5 },
    { number: '38.6', name: 'JTV', serviceId: 8 },
    { number: '38.11', name: 'GDT', serviceId: 13 },
    { number: '39.1', name: 'PBS FW', serviceId: 1 },
    { number: '39.2', name: 'PBSKIDS', serviceId: 2 },
    { number: '39.3', name: 'CREATE', serviceId: 3 },
    { number: '39.4', name: 'World', serviceId: 4 },
    { number: '39.5', name: 'PBS WX', serviceId: 5 },
    { number: '39.6', name: 'PBS ARS', serviceId: 6 },
    { number: '55.1', name: 'WFFT-TV', serviceId: 3 },
    { number: '55.2', name: 'Bounce', serviceId: 4 },
    { number: '55.3', name: 'Antenna', serviceId: 5 },
    { number: '16.1', name: 'WCUH-LD', serviceId: 1001 },
    { number: '16.2', name: 'WCUH-LD', serviceId: 1002 },
    { number: '16.3', name: 'WCUH-LD', serviceId: 1003 },
    { number: '16.4', name: 'WCUH-LD', serviceId: 1004 },
    { number: '16.5', name: 'WCUH-LD', serviceId: 1005 },
    { number: '16.6', name: 'WCUH-LD', serviceId: 1006 },
    { number: '16.7', name: 'WCUH-LD', serviceId: 1007 },
    { number: '21.1', name: 'WPTAABC', serviceId: 1 },
    { number: '21.2', name: 'WPTANBC', serviceId: 2 },
    { number: '21.3', name: 'WPTAMY', serviceId: 3 },
    { number: '15.1', name: 'WANE-HD', serviceId: 3 },
    { number: '15.2', name: 'ION', serviceId: 4 },
    { number: '15.3', name: 'LAFF', serviceId: 5 },
    { number: '15.4', name: 'Escape', serviceId: 6 },
    { number: '33.1', name: 'WISECW', serviceId: 1 },
    { number: '33.2', name: 'Justice', serviceId: 2 },
    { number: '33.3', name: 'Grit', serviceId: 3 },
    { number: '33.4', name: 'CourtTV', serviceId: 4 },
    { number: '33.5', name: 'Start', serviceId: 5 },
    { number: '33.6', name: 'MeTV', serviceId: 6 },
    { number: '33.7', name: 'DABL', serviceId: 7 }
];

// Helper to get an available tuner
function getFreeTuner() {
    return TUNERS.find(t => !t.inUse);
}

// Generate M3U Playlist
app.get('/lineup.m3u', (req, res) => {
    let m3u = '#EXTM3U\n';
    const host = req.headers.host;

    CHANNELS.forEach(channel => {
        m3u += `#EXTINF:-1 tvg-id="${channel.number}" tvg-name="${channel.name}",${channel.name}\n`;
        m3u += `http://${host}/stream/${channel.number}\n`;
    });

    res.set('Content-Type', 'audio/x-mpegurl');
    res.send(m3u);
});

// Stream Endpoint
app.get('/stream/:channelNum', (req, res) => {
    const channelNum = req.params.channelNum;
    const channel = CHANNELS.find(c => c.number === channelNum);

    if (!channel) {
        return res.status(404).send('Channel not found');
    }

    const tuner = getFreeTuner();
    if (!tuner) {
        return res.status(503).send('No tuners available');
    }

    console.log(`Starting stream for ${channel.name} on Tuner ${tuner.id}`);
    tuner.inUse = true;

    // Path to your dvb channel configuration file (generated by dvbv5-scan)
    const CHANNELS_CONF = process.env.CHANNELS_CONF || '/etc/dvb/channels.conf';

    // 1. Start dvbv5-zap to tune the frontend
    // Arguments:
    // -c : configuration file
    // -r : set up /dev/dvb/adapterX/dvr0 for recording/streaming
    // -a : adapter index
    // <channel_name> : exact name from the config file
    const zap = spawn('dvbv5-zap', [
        '-c', CHANNELS_CONF,
        '-r',
        '-a', tuner.id,
        channel.name
    ]);

    zap.on('error', (err) => {
        console.error(`Tuner ${tuner.id} zap error:`, err);
        // If zap fails to start, cleanup immediately
        cleanup();
        if (!res.headersSent) res.status(500).send('Tuner error');
    });

    // Wait slightly for lock? Or just start ffmpeg immediately. 
    // Usually safe to start ffmpeg immediately as it will block on reading dvr0 until data arrives.

    // 2. Start ffmpeg to read from dvr0 and pipe to response
    const dvrPath = `${tuner.adapter}/dvr0`;

    // FFmpeg options:
    // -analyzeduration/probesize: limit startup latency
    // -i : input path
    // -c copy : copy stream (fix .ts errors naturally by repacking)
    // -f mpegts : output format
    // pipe:1 : output to stdout
    const ffmpeg = spawn('ffmpeg', [
        '-analyzeduration', '1000000',
        '-probesize', '1000000',
        '-i', dvrPath,
        '-c', 'copy',
        '-f', 'mpegts',
        'pipe:1'
    ]);

    res.writeHead(200, {
        'Content-Type': 'video/mp2t',
        'Connection': 'keep-alive'
    });

    ffmpeg.stdout.pipe(res);

    // Logging helpers
    ffmpeg.stderr.on('data', (data) => console.log(`FFmpeg [Tuner ${tuner.id}]: ${data}`));
    zap.stderr.on('data', (data) => console.log(`Zap [Tuner ${tuner.id}]: ${data}`));

    // Cleanup function
    const cleanup = () => {
        if (tuner.cleaningUp) return;
        tuner.cleaningUp = true;

        console.log(`Cleaning up Tuner ${tuner.id} (zap PID: ${zap.pid})`);

        // Kill processes
        // Use SIGKILL for zap if it doesn't exit quickly to ensure lock release
        zap.kill('SIGTERM');
        ffmpeg.kill('SIGTERM');

        // Safety timeout to force release if processes hang
        setTimeout(() => {
            if (tuner.inUse) {
                console.warn(`Force releasing Tuner ${tuner.id} after timeout`);
                try { zap.kill('SIGKILL'); } catch (e) { }
                try { ffmpeg.kill('SIGKILL'); } catch (e) { }
                tuner.inUse = false;
                tuner.cleaningUp = false;
            }
        }, 2000);
    };

    // release tuner only when zap exits (lock released)
    zap.on('exit', (code, signal) => {
        console.log(`Zap exited [Tuner ${tuner.id}] (code: ${code}, signal: ${signal})`);
        if (tuner.inUse) {
            tuner.inUse = false;
            tuner.cleaningUp = false;
            console.log(`Tuner ${tuner.id} marked as FREE`);
        }
    });

    ffmpeg.on('exit', (code) => {
        console.log(`FFmpeg exited [Tuner ${tuner.id}] with code ${code}`);
        // If ffmpeg dies, we must kill zap to stop tuning
        cleanup();
    });

    // Client disconnect
    req.on('close', () => {
        console.log(`Client disconnected [Tuner ${tuner.id}]`);
        cleanup();
    });

    // Handle zap errors
    zap.on('error', (err) => {
        console.error(`Tuner ${tuner.id} zap error:`, err);
        cleanup();
    });
});

app.listen(PORT, () => {
    console.log(`Tuner app listening at http://localhost:${PORT}`);
});
