const express = require('express');
const { spawn } = require('child_process');
const fs = require('fs');

const app = express();
const PORT = process.env.PORT || 3000;

// Tuner Configuration
// Adjust these adapter paths based on your system (e.g., /dev/dvb/adapter0, /dev/dvb/adapter1)
const TUNERS = [
    { id: 0, adapter: '/dev/dvb/adapter0', inUse: false },
    { id: 1, adapter: '/dev/dvb/adapter1', inUse: false }
];

// Mock Channel List - Replace with actual frequency data
const CHANNELS = [
    { number: '1.1', name: 'Channel One', frequency: '517000000', programId: '1' },
    { number: '2.1', name: 'Channel Two', frequency: '523000000', programId: '2' }
    // Add more channels here
];

// Helper to get an available tuner
function getFreeTuner() {
    return TUNERS.find(t => !t.inUse);
}

// Generate M3U Playlist
app.get('/lineup.m3u', (req, res) => {
    let m3u = '#EXTM3U\n';
    const host = req.headers.host;

    CHANNELS.forEach(channel => {
        m3u += `#EXTINF:-1 tvg-id="${channel.number}" tvg-name="${channel.name}",${channel.name}\n`;
        m3u += `http://${host}/stream/${channel.number}\n`;
    });

    res.set('Content-Type', 'audio/x-mpegurl');
    res.send(m3u);
});

// Stream Endpoint
app.get('/stream/:channelNum', (req, res) => {
    const channelNum = req.params.channelNum;
    const channel = CHANNELS.find(c => c.number === channelNum);

    if (!channel) {
        return res.status(404).send('Channel not found');
    }

    const tuner = getFreeTuner();
    if (!tuner) {
        return res.status(503).send('No tuners available');
    }

    console.log(`Starting stream for ${channel.name} on Tuner ${tuner.id}`);
    tuner.inUse = true;

    // Path to your dvb channel configuration file (generated by dvbv5-scan)
    const CHANNELS_CONF = process.env.CHANNELS_CONF || '/etc/dvb/channels.conf';

    // 1. Start dvbv5-zap to tune the frontend
    // Arguments:
    // -c : configuration file
    // -r : set up /dev/dvb/adapterX/dvr0 for recording/streaming
    // -a : adapter index
    // <channel_name> : exact name from the config file
    const zap = spawn('dvbv5-zap', [
        '-c', CHANNELS_CONF,
        '-r',
        '-a', tuner.id,
        channel.name
    ]);

    zap.on('error', (err) => {
        console.error(`Tuner ${tuner.id} zap error:`, err);
        // If zap fails to start, cleanup immediately
        cleanup();
        if (!res.headersSent) res.status(500).send('Tuner error');
    });

    // Wait slightly for lock? Or just start ffmpeg immediately. 
    // Usually safe to start ffmpeg immediately as it will block on reading dvr0 until data arrives.

    // 2. Start ffmpeg to read from dvr0 and pipe to response
    const dvrPath = `${tuner.adapter}/dvr0`;

    // FFmpeg options:
    // -analyzeduration/probesize: limit startup latency
    // -i : input path
    // -c copy : copy stream (fix .ts errors naturally by repacking)
    // -f mpegts : output format
    // pipe:1 : output to stdout
    const ffmpeg = spawn('ffmpeg', [
        '-analyzeduration', '1000000',
        '-probesize', '1000000',
        '-i', dvrPath,
        '-c', 'copy',
        '-f', 'mpegts',
        'pipe:1'
    ]);

    res.writeHead(200, {
        'Content-Type': 'video/mp2t',
        'Connection': 'keep-alive'
    });

    ffmpeg.stdout.pipe(res);

    // Logging helpers
    ffmpeg.stderr.on('data', (data) => console.log(`FFmpeg [Tuner ${tuner.id}]: ${data}`));
    zap.stderr.on('data', (data) => console.log(`Zap [Tuner ${tuner.id}]: ${data}`));

    // Cleanup function
    const cleanup = () => {
        console.log(`Cleaning up Tuner ${tuner.id}`);
        if (!tuner.inUse) return; // Already cleaned up

        tuner.inUse = false;

        // Kill processes
        zap.kill('SIGTERM');
        ffmpeg.kill('SIGTERM');
    };

    // Client disconnect
    req.on('close', cleanup);

    // Process exits
    ffmpeg.on('exit', (code) => {
        console.log(`FFmpeg exited with code ${code}`);
        cleanup();
    });
    zap.on('exit', (code) => {
        console.log(`Zap exited with code ${code}`);
        cleanup(); // If zap dies, stream is dead
    });
});

app.listen(PORT, () => {
    console.log(`Tuner app listening at http://localhost:${PORT}`);
});
